#!/bin/sh

dirs=()
while [ $# -gt 0 ]
do
  dirs+=($1)
  shift
done

if [ ${#dirs[@]} -eq 0 ]; then
  dirs=`ls -d ~/Desktop/work/*`
fi

for dir in ${dirs[@]}
do
  if [ -e "${dir}/.git" ]; then
    echo $dir
  fi
done |
  while read dir
  do
    current_dir=`pwd`
    cd $dir > /dev/null
    git --no-pager log --date=short --pretty=format:"%ad"
    echo
    cd $current_dir > /dev/null
  done | git-contrib-cal.rb
